Feature/sym 2935/datepicker
SymphonyPlatformSolutions/symphony-bdk-ui-toolkit pull request #112
Opened 2020-12-09 08:04 UTC by AnthonyDS-symphony

2020-12-09 09:18 UTC, vanhauphan commented on src/components/inputs/datepickerv2/day/theme.js
> +    return '#008EFF';
same question for dark and light theme compatibility

2020-12-09 09:18 UTC, vanhauphan commented on src/components/inputs/datepickerv2/day/theme.js
> +    background-color: #fff;
same color question here

2020-12-09 09:18 UTC, vanhauphan commented on src/components/inputs/datepickerv2/header/index.js
> +const CHEVRON_COLOR = '#008EFF';
and here

2020-12-09 09:40 UTC, AnthonyDS-symphony commented on src/components/inputs/datepicker/Day.js
> +        className="day-button"
Just added a className attribute in order to retrieve this DOM element easier but this class isn't used as well.
I'll remove it, thanks!

2020-12-09 13:50 UTC, daitan-rovaris commented on src/components/inputs/datepicker/Day.js
> +        className="day-button"
you could use a data-test-id if you want a selector

2020-12-09 14:06 UTC, JulienBlacas requested changes
@AnthonyDS-symphony Good job 🚀  ! Please see my comments

2020-12-09 14:06 UTC, JulienBlacas commented on src/components/inputs/datepickerv2/month/index.js
> +        {days.map((day) => (
@AnthonyDS-symphony For some reason, the two first values of days array are 0.
To avoid rendering empty components and getting the error `Each child in a list should have a unique "key"` we can change it like this. I assume it has something to do with the firstDayOfWeek prop : https://github.com/tresko/react-datepicker/tree/master/packages/hooks#firstdayofweek-number--undefined-default-1


```suggestion
        {days.map((day) => (
            day.dayLabel && (<Day key={day.dayLabel} date={day.date} day={day.dayLabel} />)
        ))}
```

2020-12-09 14:06 UTC, JulienBlacas commented on src/components/inputs/datepickerv2/utils.js
> +  const dateAreDifferent = methods
@AnthonyDS-symphony Do you mean dateAreEquals ? because it's what is checked here

2020-12-09 15:46 UTC, AnthonyDS-symphony commented on src/components/inputs/datepicker/bubble.js
> +      {footerNavigationButtons.length !== 0 && (
@JulienBlacas, we shouldn't do that.
Actually, when the array is empty, React will draw "0" in the DOM.

You can try:

`{[].length && <p>Do Work</p>}`

2020-12-09 15:51 UTC, JulienBlacas commented on src/components/inputs/datepicker/bubble.js
> +      {footerNavigationButtons.length !== 0 && (
@AnthonyDS-symphony Yes my bad, I always have my old habits with pure js 👍

2020-12-09 15:52 UTC, AnthonyDS-symphony commented on src/components/inputs/datepicker/Day.js
> +        className="day-button"
@daitan-rovaris Agree. I created this className for me, in order to find the element visually not programatically ;)
Thanks for you comment!

2020-12-10 14:46 UTC, JulienBlacas approved these changes

2020-12-10 14:52 UTC, merged